import { getServerSession } from "next-auth";
import { useTranslations } from 'next-intl';
import { redirect } from "next/navigation";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

import BarChart from '../components/admin/BarChart';
import Header from '../components/admin/Header';
import Sidebar from '../components/admin/Sidebar';
import RecentOrders from '../components/admin/RecentOrders';
import TopCards from '../components/admin/TopCards';

export const metadata = {
    title: 'KDPLAYBACK | DASHBOARD',
    description: 'KDPLAYBACK',
    keywords: 'subcribe youtube ranking, hololive, vtuber, pewdiepie, nextjs',
    viewport: 'width=device-width',
    openGraph: {
        title: 'Twitter',
        description: 'Generated by create next app Twitter',
    }
}

export default async function Dashboard() {

    // Check login (NextJS, MongoDB, use signIn)
    // const session = await getServerSession(authOptions);
    // if (session == null || session == undefined) redirect("/login");

    return (
        <div className='flex'>
            <Sidebar />
            <main className='ml-20 w-full'>
                <div className='bg-gray-100 min-h-screen'>
                    <Header />
                    <TopCards />
                    <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
                        <BarChart />
                        <RecentOrders />
                    </div>
                </div>
            </main>
        </div>
    )
}
